build: off

cache:
 - "%LOCALAPPDATA%\\Yarn"

environment:
  matrix:
    - nodejs_version: '10'
      test_script: 'test'
    - nodejs_version: '8'
      test_script: 'test'
    - nodejs_version: '6'
      test_script: 'test'

install:
  - ps: Install-Product node $env:nodejs_version
  - yarn install

test_script:
  - node --version
  - yarn --version
  - yarn run %test_script%
